#
# This source file is part of the Stanford Spezi open-source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  packageios:
    name: Build and Test Swift Package iOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: SpeziNetworking-Package
      resultBundle: SpeziNetworking-iOS.xcresult
      artifactname: SpeziNetworking-iOS.xcresult
  packagewatchos:
    name: Build and Test Swift Package watchOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: SpeziNetworking-Package
      destination: 'platform=watchOS Simulator,name=Apple Watch Series 9 (45mm)'
      resultBundle: SpeziNetworking-watchOS.xcresult
      artifactname: SpeziNetworking-watchOS.xcresult
  packagevisionos:
    name: Build and Test Swift Package visionOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: SpeziNetworking-Package
      destination: 'platform=visionOS Simulator,name=Apple Vision Pro'
      resultBundle: SpeziNetworking-visionOS.xcresult
      artifactname: SpeziNetworking-visionOS.xcresult
  packagetvos:
    name: Build and Test Swift Package tvOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: SpeziNetworking-Package
      resultBundle: SpeziNetworking-tvOS.xcresult
      destination: 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation)'
      artifactname: SpeziNetworking-tvOS.xcresult
  packagemacos:
    name: Build and Test Swift Package macOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: SpeziNetworking-Package
      resultBundle: SpeziNetworking-macOS.xcresult
      destination: 'platform=macOS,arch=arm64'
      artifactname: SpeziNetworking-macOS.xcresult
  codeql:
    name: CodeQL
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      codeql: true
      test: false
      scheme: SpeziNetworking-Package
    permissions:
      security-events: write
      actions: read
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [packageios, packagewatchos, packagevisionos, packagetvos, packagemacos, ios, ipados, watchos, visionos, tvos]
    uses: StanfordSpezi/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: SpeziNetworking-iOS.xcresult SpeziNetworking-watchOS.xcresult SpeziNetworking-visionOS.xcresult SpeziNetworking-tvOS.xcresult SpeziNetworking-macOS.xcresult
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}
